### ISSUE TITLE
Maximise height or width only with animation

### ISSUE THREAD

**Issue by CallumHoward** [anuvyklack/windows.nvim#15]
I love the animations in this plugin!

Currently I'm quite used to using `<C-w>_` and `<C-w>|` to maximise the current window split in either the vertical or horizontal axis respectively. I typically then use `<C-w>=` to restore.

I would love if this plugin could add functions that I could remap the above to in order to achieve animated versions.

Or even better, I like the toggle behavior of `:WindowsMaximize`, it would be great if something like `:WindowsMaximizeVertical` and `:WindowsMaximizeHorizontal` could also toggle between maximising and equalising.

**Comment by anuvyklack** [comment]
Nice suggestion! Done
