### ISSUE TITLE
Proposal: Create an option to auto-maximize the active window when autowidth is enabled

### ISSUE THREAD

**Issue by kingtaj** [anuvyklack/windows.nvim#16]
For example, I often work with a few vertical panes. Currently, when moving between them, the active pane gets slightly wider, but I'd like to have it automatically expand to the "maximized" size.

**Comment by kingtaj** [comment]
Please disregard - this is the expected behavior and I had a configuration issue preventing it from working properly.

**Comment by benwoodward** [comment]
> Please disregard - this is the expected behavior and I had a configuration issue preventing it from working properly.

how did you resolve this?
