### ISSUE TITLE
Can not find all commands

### ISSUE THREAD

**Issue by lost22git** [anuvyklack/windows.nvim#20]
Can not find all commands of the plugin

![image](https://user-images.githubusercontent.com/65008815/196011184-f7f5ff37-2712-4e1f-8589-a68d44593e4a.png)

![image](https://user-images.githubusercontent.com/65008815/196011345-9f317536-4be9-47d7-b840-63ad80bf1f8c.png)

installed path

![image](https://user-images.githubusercontent.com/65008815/196011242-656592e7-55c3-42fe-bdc3-22beaafe5b4c.png)

and i can not find the plugin by run `:PackerStatus`

- packer config
```lua
use { "anuvyklack/windows.nvim",
  requires = {
    "anuvyklack/middleclass",
    "anuvyklack/animation.nvim"
  },
  config = function()
    vim.o.winwidth = 10
    vim.o.winminwidth = 10
    vim.o.equalalways = false
    require('windows').setup()
  end
}
```
- os: win11
- neovim version:
 ```
  NVIM v0.8.0-1210-gd367ed9b2
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  Compiled by runneradmin@fv-az177-603
  ```

**Comment by anuvyklack** [comment]
It seems, that the problem is on the `packer` side, because `windows.nvim` hadn't been loaded, hence no `windows.nvim` code been executed.

**Comment by nicolimo86** [comment]
I have the same issue. Does it mean that this plugin can't be installed using Packer?

**Comment by lost22git** [comment]
@nicolimo86 

maybe you need to rename windows.lua with another name if exists windows.lua in you config path

**Comment by nicolimo86** [comment]
@lost22git 
I looked in couple of palces, and found something:
`find .config/nvim/ -iname "windows.lua"` - no results.

`find .local/ -iname "windows.lua"
.local/share/nvim/site/pack/packer/start/nvim-lspconfig/lua/lspconfig/ui/windows.lua`

Although, I'm not sure that plays a role for this particular problem.
So, for what I understand I have some name conflict somewhere in my config (even if I don't see it, yet..).
I'll try to isolate the issue in the limits of my possibilities. If you have any useful hint, please don't hesitate.

**Comment by nicolimo86** [comment]
It was sufficient to perform a manual reload using `:lua require('windows').setup()` to see appearing all the commands in the execution bar.
I specified the same command in my init.lua, and now everything looks as it should.
