### ISSUE TITLE
bug? split-resizing works at laptop-resolution, but at larger resolution they remain equally sized

### ISSUE THREAD

**Issue by benwoodward** [anuvyklack/windows.nvim#22]
At 2560x1440 it doesn't matter what `winwidth` and `winminwidth` settings I use, the splits will just equalise in size, however, at lower resolutions, I don't have this problem.

![CleanShot 2022-10-26 at 18 33 49](https://user-images.githubusercontent.com/1472981/197943244-1166bed0-9216-4773-937d-2ad0841b78e0.gif)

**Comment by anuvyklack** [comment]
This is intended behavior. See `winwidth` option (`:help windows.winwidth`). If you don't understand, write here, I will try to explain.

**Comment by benwoodward** [comment]
the problem was that I didn't have a `textwidth` value set. I fixed my issue with `vim.o.textwidth = 100`
