### ISSUE TITLE
:WindowsMaximize works on vertical splits, but doesn't on horizontal ones

### ISSUE THREAD

**Issue by nicolimo86** [anuvyklack/windows.nvim#24]
Working scenario:
1) Open neovim and create a vertical split with `:vs`.
2)  `:WindowsMaximize` will work as expected.

Not working scenario:
1) Open neovim and create a horizontal split with `:sp`.
2)  `:WindowsMaximize` does not do anything.

**Comment by anoopd** [comment]
Sorry to bother you agin   ....... the problem prevails with a small difference . `:WindowsMaximize` does work in horizontal split but it doesn't work automatically as in vertical splits . Is there something to be done other than that in the config example
