### ISSUE TITLE
Make `animation.nvim` optional

### ISSUE THREAD

**Issue by vulns-are-features-too** [anuvyklack/windows.nvim#4]
This seems interesting and can replace `szw/vim-maximizer` but I generally don't want fancy animations in my terminal - just instant movements. Since not everyone wants smooth animations, I think `animation.nvim` should be an optional dependency - only required if the user explicitly wants animations. This should reduce the dependencies and bloat.

**Comment by anuvyklack** [comment]
`animation.nvim` is optional. I should make it clear in Readme.
