### ISSUE TITLE
Do not autowidth when enough space.

### ISSUE THREAD

**Issue by thekaganugur** [anuvyklack/windows.nvim#5]
Hi,
It's working great on my 14" built-in monitor but when I switch to 24" there is enough room for two vertical splits. Autowidth still tries to re-arrange windows and it feels like a glitch. Split grows and shrinks 2-3px.

**Comment by anuvyklack** [comment]
Due to terminal nature, Neovim can't change window width in 2-3px because the smallest unit is a cell. And there is already built-in not to change size of the window if it has desired width or more. What configuration of `windows.nvim` do you use?

**Comment by thekaganugur** [comment]
I probably explained it wrong. It's now fixed with [21cd08f](https://github.com/anuvyklack/windows.nvim/commit/8685cd0869fe631820fda376e9f7faa0618cc059).

Thank you for the work.
