### ISSUE TITLE
Slight "flicker" when moving between two windows of equal width

### ISSUE THREAD

**Issue by smjonas** [anuvyklack/windows.nvim#9]
Hey, thanks for this great plugin, very useful! I have found a slight annoyance when switching between two equally-sized splits that are opened side by side in fullscreen. See this GIF:

![windows_nvim](https://user-images.githubusercontent.com/40792180/191065284-e74f5bf8-10df-4666-bb00-781fba991303.gif)

Maybe this is a result of rounding up / down to the nearest integer? Can this perhaps be made more stable so there is no resize?

Here is my config:
```lua
config = function()
  require("windows").setup {
    animation = {
      enable = false,
    },
  }
end,
```

**Comment by anuvyklack** [comment]
Fixed in 8685cd0
